---
- name: Set system hostname
  hostname: "name={{ hostname }}"
  become: yes
  when: hostname != ""

- name: Generate locales
  locale_gen: "name={{ item }} state=present"
  with_items:
    - en_US
    - en_US.UTF-8
    - en_CA
    - en_CA.UTF-8
  become: yes

- name: Add git PPA
  apt_repository: repo=ppa:git-core/ppa update_cache=yes
  become: yes

- name: Install git latest
  apt: pkg=git state=latest
  become: yes

- name: Install dev tools
  apt: "pkg={{ item }} state=present"
  with_items:
      - exuberant-ctags
      - ruby
      - silversearcher-ag
      - sqlite3
      - tree
      - unzip
      - vim
      - zsh
  become: yes

- name: Create user with zsh as default shell
  user: "name={{ username }} shell=/usr/bin/zsh"
  become: yes

- name: Add tmux PPA
  apt_repository: repo=ppa:mpanella/tmux update_cache=yes
  become: yes

- name: Install tmux latest
  apt: pkg=tmux state=latest
  become: yes

- name: Clone dotfiles
  git:
    repo: https://github.com/jswinarton/dotfiles.git
    dest: "/home/{{ username }}/apps/dotfiles"
    update: no
  become: yes
  become_user: "{{ username }}"

- name: Setup dotfiles
  command: "/home/{{ username }}/apps/dotfiles/etc/setup creates=/home/{{ username }}/.commonrc"
  become: yes
  become_user: "{{ username }}"
