---
- name: Set system hostname
  hostname: "name={{ hostname }}"
  become: yes
  when: hostname != ""

- name: Generate locales
  locale_gen: "name={{ item }} state=present"
  with_items:
    - en_US
    - en_US.UTF-8
    - en_CA
    - en_CA.UTF-8
  become: yes
  when: generate_locales == true

- name: Create user
  user: "name={{ username }}"
  become: yes

- include: tasks/utils.yml
  when: minimal == false

- name: Clone dotfiles
  git:
    repo: https://github.com/jswinarton/dotfiles.git
    dest: "/home/{{ username }}/apps/dotfiles"
    update: no
  become: yes
  become_user: "{{ username }}"

- name: Setup dotfiles
  command: "/home/{{ username }}/apps/dotfiles/etc/setup creates=/home/{{ username }}/.commonrc"
  become: yes
  become_user: "{{ username }}"
